### ISSUE TITLE
Update and Change Calendar data

### ISSUE THREAD

**Issue by nouranianfar** [SeBassTian23/CalendarHeatmap#1]
Dear

I want to update calendar data real time with script.
My data if change I could not update calendar data.

thanks

**Comment by SeBassTian23** [comment]
I apologize for the long silence! Can you provide an example of your code?

**Comment by Xymph** [comment]
Like this heatmap-variant more than others because months are shown separately and it has a nice set of customization options.

But I have the same problem. Script:
```
function refresh()
{
  $('<my selector>').each( function() {
    /*$('#act' + $(this).html()).html('');*/
    $.ajax({
      url: '<script returning JSON>.php',
      type: 'GET',
      data: {
        year: $(this).html(),
        <name1>: $('input[name=<inputname1>]').val(),
        <name2>: $('input[name=<inputname2>]').val(),
      },
      dataType: 'json',

      success: function(result) {
        $('#act' + result.year).CalendarHeatmap(result.data, {
          lastMonth: 12,
          lastYear: result.year,
          /* more cosmetic options */
        });
      }
    });
  });
}

$(function() {
  refresh();
});
```
At page load, the heatmaps are rendered. There's a form with two input fields that also invoke 'refresh()' at the onchange event. I can see the Ajax calls returning the expected data, but the heatmaps aren't refreshed with the changed data sets. If I then reload the page (preserving form values), the updated heatmaps are rendered as yet.

If I enable the commented-out html('') call to clear the divs, the heatmaps are removed at onchange, but no new ones are rendered.

Could this be caused by the main "this.calendarHeatmap();" call being invoked only from the plugin's "init:" method?

Btw, in step 6 [here](https://www.jqueryscript.net/chart-graph/Calendar-Heatmap-Plugin-jQuery.html), the tiles option with its values could be documented.

**Comment by SeBassTian23** [comment]
Thank you for the detailed description of the issue. I will try to update the plugin ASAP. 

Regarding the link you have provided. I think the issue is that this service is not updating the Readme file. Please find everything documented including the tiles [here](https://github.com/SeBassTian23/CalendarHeatmap).

**Comment by Xymph** [comment]
That was encouraging to read -- any progress?
Even if my use of the heatmap plugin is only in a private, non-vital application, I'd love it if refreshing works as expected.

**Comment by excel-vba-course** [comment]
Hey mate - also was wondering about how to achieve updating of control with a different dataset. Do you have a workaround to achieve this ?

Thanks in advance

**Comment by SeBassTian23** [comment]
I found some time to work on the plugin and the functions to update the dates (data) and the options are available with the latest release (v.1.2.0) now.

**Comment by Xymph** [comment]
I updated my application just now, and updateDates does the job. Thanks a lot!

**Comment by SeBassTian23** [comment]
I'm glad it is working for you now.
